### ISSUE TITLE
Error: dependent module not loaded: io.picolabs.pico

### ISSUE THREAD

**Issue by scwood** [Picolab/node-pico-engine#9]
This happens right when I try to run `pico-engine` after a fresh install.

```
$ pico-engine
/usr/local/lib/node_modules/pico-engine/src/index.js:16
            throw err;
            ^

Error: Dependant module not loaded: io.picolabs.pico
    at /usr/local/lib/node_modules/pico-engine/node_modules/pico-engine-core/src/index.js:123:23
    at Generator.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/pico-engine/node_modules/co/index.js:65:19)
```

- macOS 10.12.1
- node 7.5.0

Any quick fix in the meantime so I can finish the lab?

**Comment by b1conrad** [comment]
What version of pico-engine-core do you have?

```
$ npm ls -g pico-engine-core
/usr/local/lib
└─┬ pico-engine@0.5.7
  └── pico-engine-core@0.21.4 

```

**Comment by farskipper** [comment]
We had a race condition in the registering rulesets. I just fixed it and released a new version 0.5.9
```sh
$ npm update -g pico-engine
$ npm ls -g pico-engine
/usr/local/lib
└── pico-engine@0.5.9 
```
If you see the new version, then you should be good to go.

**Comment by scwood** [comment]
This still isn't working for me. I've tried on node v4, v6, and v7.
 
```
$ pico-engine
/usr/local/lib/node_modules/pico-engine/src/index.js:16
            throw err;
            ^

Error: Dependant module not loaded: io.picolabs.pico
    at /usr/local/lib/node_modules/pico-engine/node_modules/pico-engine-core/src/index.js:123:23
    at Generator.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/pico-engine/node_modules/co/index.js:65:19)
$ npm ls -g pico-engine
/usr/local/lib
└── pico-engine@0.5.9
```

**Comment by farskipper** [comment]
Try clearing the db then start it again
```
$ rm -rf ~/.pico-engine/
```

**Comment by scwood** [comment]
Thanks, that worked!
